# Generated by Django 3.1 on 2020-08-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_consultant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('old', 'Old'), ('defect', 'Defect'), ('special', 'Special')], max_length=20)),
                ('coef', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sales'),
        ),
    ]
