# Generated by Django 3.1 on 2020-08-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200807_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='types',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
