# Generated by Django 3.1 on 2020-08-08 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200807_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sales'),
        ),
    ]
