# Generated by Django 3.1 on 2020-08-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200808_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='priority',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
